rules = [
  ExplicitResultTypes,
  LeakingImplicitClassVal,
  NoValInForComprehension,
  ProcedureSyntax,
  RemoveUnused,
  DisableSyntax,
  OrganizeImports,
  RedundantSyntax,
]

ExplicitResultTypes {
  fetchScala3CompilerArtifactsOnVersionMismatch = true
}

OrganizeImports {
  groupedImports = Keep
  groups = ["*", "re:(javax?|scala)\\.", "net.ghoula.longbow"]
  removeUnused = true
  targetDialect = Scala3
}

DisableSyntax {
  noVars = true
  noThrows = true
  noNulls = true
  noReturns = true
  noIsInstanceOf = true
  noFinalVal = true
  noFinalize = true
  noCovariant = true
  noContravariant = true
  noAsInstanceOf = true
}

// Allow vars and throws in tests
DisableSyntax.noVars = false
DisableSyntax.noThrows = false
